---
- hosts: all
  become: true
  roles:
  - role/bootstrap
  - role/mariadb
  - role/nginx
  - role/phpmyadmin
  - role/postfix
  - role/php
  - role/composer
  - role/elasticsearch
  - role/magento
